# 스프링 부트 서버가 실행되면 자동으로 로딩되는 파일
spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb

  # 실제 데이터를 확인하기 위해 H2 콘솔을 활성화
  h2:
    console:
      enabled: true

jwt:
  issuer: Team_HeartBeat
  secret_key: study-connection
